### PR TITLE
Full editor

### PR DESCRIPTION
**Pull request by mciissee**

### CODE REVIEW

**Comment by nimdanor** [comment]
@qcoumes what do you mean ?

**Comment by mciissee** [comment]
@qcoumes all the tests of 0.5.0 are merged and tested with full_editor branch expects the ones from filebrowser module because they are not compatible with the way filebrowser works now

**Comment by qcoumes** [comment]
Ok, everything is working properly now. I did some tests, only views.py remain.

**Comment by nborie** [comment]
https://www.youtube.com/watch?v=CSav51fVlKU

**Pull request merged**
